let books = {
      1: {"author": "Chinua Achebe","title": "Things Fall Apart", 
            "isbn": "9780141023380", "reviews": {} },
      2: {"author": "Hans Christian Andersen","title": "Fairy tales", 
            "isbn": "0517092913", "reviews": {} },
      3: {"author": "Dante Alighieri","title": "The Divine Comedy", 
            "isbn": "9780141197494", "reviews": {} },
      4: {"author": "Andrew George","title": "The Epic Of Gilgamesh", 
            "isbn": "9780140449198", "reviews": {
              1: {"headline": "Building Something That Lasts", 
                  "content": "The Epic of Gilgamesh, dating to 2100 BC, tells the story of Gilgamesh, king of the city of Uruk, who, demented with grief following the death of a friend, goes on a journey in search of eternal life.", 
                  "reviewer": "Martin Jones"},
              2: {"headline": "A wonderful translation of an important text", 
                  "content": "Gilgamesh is not always easy reading: the text is fragmentary, the meaning sometimes unclear, the composition repetitive and replete with lists. That said it contains so much that is beautiful: friendship, love, existential fear of death, sex, adventure, myth, fighting against odds, the source myths for Noah, but with Gods who see the horror of mass murder and an ocean full of corpses in a way that Genesis misses etc. etc.", 
                  "reviewer": "James D"},
              3: {"headline": "Very small print", 
                  "content": "I would have given this remarkable and interesting book five stars. However the print of the Penguin edition is very small. However despite this, it is worth struggling to read the book. There is so much scholarship and research that has gone into Professor Andrew George's study of the period that this alone makes the book a must. His style is engaging and delightfully presented. The pictures that illustrate the text have been carefully chosen and add to the general effect.", 
                  "reviewer": "Malcolm U"},
              4: {"headline": "but worth the perseverance - good background​ information", 
                  "content": "Heavy going, but worth the perseverance - good background​ information.", 
                  "reviewer": "Bobo"},
              5: {"headline": "A whole new world", 
                  "content": "The Epic of Gilgamesh and the literature from the ANE takes you to a whole new world. Just the introduction is worth more than the price of this book. Andrew George's scholarship is Top notch.",
                  "reviewer": "Suraj Lama"},
            } },
      5: {"author": "Unknown","title": "The Book Of Job", 
            "isbn": "", "reviews": {} },
      6: {"author": "Unknown","title": "One Thousand and One Nights", 
            "isbn": "", "reviews": {} },
      7: {"author": "Unknown","title": "Nj\u00e1l's Saga", 
            "isbn": "", "reviews": {} },
      8: {"author": "Jane Austen","title": "Pride and Prejudice", 
            "isbn": "", "reviews": {} },
      9: {"author": "Honor\u00e9 de Balzac","title": "Le P\u00e8re Goriot", 
            "isbn": "", "reviews": {} },
      10: {"author": "Samuel Beckett","title": "Molloy, Malone Dies, The Unnamable, the trilogy", 
            "isbn": "", "reviews": {} }
}

module.exports=books;
